### ISSUE TITLE
Threshold for marker grouping is too low

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#102]
Should be at least 3 I think.

**Comment by eliemichel** [comment]
As I said in #81, I used ClusterMarker out of the box, without changing any parameter.

So feel free to customize it! (Plus, I agree, it's too low)

**Comment by Phyks** [comment]
Does not look feasible at the moment: https://github.com/Leaflet/Leaflet.markercluster/issues/399

**Comment by eliemichel** [comment]
You cannot do it depending on the number, but we should at least modify the zoom level at which it is clustered.

**Comment by Phyks** [comment]
Fixed. Gives good results and no need for more complicated control on the threshold I think.
