### ISSUE TITLE
Stations markers not displayed

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#105]
When loading the app from the main menu, clicking on search, no markers are shown.

When reloading the page (hence loading directly the search view), everything works fine.

AFAIK, this is a recent regression.

**Comment by Phyks** [comment]
Same when clicking on the "show position" button on a station detailed view.

**Comment by eliemichel** [comment]
Any error in JS console?

**Comment by Phyks** [comment]
Nope =(

**Comment by eliemichel** [comment]
Wierd. Anyway, it could wait for my new branch to be merged (almost ready) as it will change this system.

**Comment by Phyks** [comment]
Ok.

**Comment by Phyks** [comment]
Fixed.
