### ISSUE TITLE
Design issue in the bottom bar with long letters

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#107]
There is an issue in the bottom bar (Search, Ajouter, Informations) with some letters.

Not sure why it happens.

In the following snapshot, it should be written "Add" but one reads "Aaa".

![2015-10-13-164010](https://cloud.githubusercontent.com/assets/3856586/10458029/240e9b38-71c9-11e5-9df7-d9e24f51776a.png)

**Comment by eliemichel** [comment]
~~Cannot reproduce. I sometimes have this kind of glitch with firefox. Do you have the same issue in chromium?~~

edit: My bad, you were already using chromium. Well, I was able to reproduce the bug then but I really don't understand it…

PS: It makes no sense that you report the bug _and_ confirm it…

**Comment by Phyks** [comment]
This happens on Chromium at default zoom level. Zooming in/out solve the issue. Firefox is not affected.

Seems that Chromium is not able to display correctly "Open Sans" here, because I don't have the issue with other fonts. Most likely a bug on chromium side no?

**Comment by eliemichel** [comment]
(I had let the label because I was saying that I have it too…)

It's suprising that Chromium have issue to display such a common font…

**Comment by Phyks** [comment]
Look like it is something like http://htmlasks.com/open_sans_thin_weight_200_from_google. We are at 200 for now and indeed, we have no defined Open Sans fonts for this weight. Same problem holds for the "Light" version (font weight of 300), and we have to go to 400 to solve it. Looks like a chromium issue and I think we can close this issue and eventually report to Chromium.
