### ISSUE TITLE
[design] No manifest

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#12]
There is no manifest in design branch.

**Comment by Phyks** [comment]
But the one from the master branch could be reused AFAIK.

**Comment by indydedeken** [comment]
Yes, we can use the same. 

Manifest file allows to test the app with the Firefox OS simulator in FirefoxDeveloperEdition. Pretty useful.
Code is ok for you (version?) : 

<pre>{
  "name": "VelibFxos",
  "version": "1.0",
  "type": "web",
  "description": "Firefox OS app for the Velib bike sharing system in Paris",
  "launch_path": "/index.html",
  "permissions": {
    "geolocation": {
      "description": "Required for sharing closest Velib stations."
      }
  },
  "developer": {
    "name": "Phyks",
    "url": "http://phyks.me"
  },
  "icons": {
    "60": "/img/icons/icon_60.png",
    "128": "/img/icons/icon_128.png",
    "256": "/img/icons/icon_256.png"
  }
}</pre>

**Comment by Phyks** [comment]
Version is still a dev version, but once fully integrated, I am okay for a 1.0 version and to release it on the Marketplace, of course ! :p

**Comment by indydedeken** [comment]
Fixed
