### ISSUE TITLE
UX suggestion

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#2]
![VelibFxos UX](https://lut.im/6qAIipyR/5EWW6P6q)

**Comment by edouardalvescamilo** [comment]
@eliemichel : Pourrait on disposer de l'ensemble des svg constituant ton modèle ?

Merci d'avance.

**Comment by eliemichel** [comment]
Bien sûr !
Je l'ai mis sur le dépôt, dans la branche design : https://github.com/Phyks/VelibFxos/blob/design/doc/mockup.svg (les parties intéressantes sortant du cadre en fait)
C'est un fichier de travail, donc un peu bordélique, mais tout y est.

PS: Je n'ai pas exporté les fontes, mais il ne me semble pas en utilisé de tordues.

**Comment by eliemichel** [comment]
This is on a good way in the `design` branch, I think we can close this now.
