### ISSUE TITLE
Replace the picture used in station details

### ISSUE THREAD

**Issue by edouardalvescamilo** [Phyks/VelibFxos#22]
We need to use the correct picture for "Station V+" in station details web page in SVG format.

I'm talking about this one : ![sans titre](https://cloud.githubusercontent.com/assets/8982186/6224796/4b39dd7e-b682-11e4-8423-a28378222874.png)

**Comment by eliemichel** [comment]
Added here: [`img/v-plus.svg`](https://github.com/Phyks/VelibFxos/blob/design/img/v-plus.svg)

**Comment by indydedeken** [comment]
@eliemichel can be closed : 70f4a681fa367169dc89a72a79d115b23564e88a :+1:
