### ISSUE TITLE
[map] Need more beautiful markers for search

### ISSUE THREAD

**Issue by indydedeken** [Phyks/VelibFxos#28]
We need more beautiful markers. One constraint, it needs to show : 
- availables bikes, color: #dc1681
- availables bike stands, color: #009bb7

![Rechercher vue](https://cloud.githubusercontent.com/assets/1382821/6446593/685b08e4-c10c-11e4-8767-6321d27d7b13.png)

**Comment by Phyks** [comment]
:+1: plus the actual one are slightly not visible enough.

**Comment by eliemichel** [comment]
I propose one of the following:

![Velib station](https://lut.im/SJOymYfE/fp3jjnty)

I prefere the third one, but feel free to comment!

**Comment by indydedeken** [comment]
Thanks for these nice markers. 
:three: for me too.

**Comment by eliemichel** [comment]
Added in [`img/station.svg`](https://github.com/Phyks/VelibFxos/blob/design/img/station.svg):
![Station](https://raw.githubusercontent.com/Phyks/VelibFxos/design/img/station.svg)

**Comment by eliemichel** [comment]
Text is not correctly centered:
![Station](https://lut.im/0SmK1n2U/gOaEFxYZ)

It could be centered on each side or right-aligned on the left hand side and left-aligned on the right hand side.
