### ISSUE TITLE
[JavaScript] object Map VS variable map

### ISSUE THREAD

**Issue by indydedeken** [Phyks/VelibFxos#29]
**Map** will become a [JavaScript object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) ([FR](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Map)). 
We should replace the variable map with something else like <code>plan</code> for example.

Edit : Replace all <code>Map</code> occurences with <code>RoadMap</code>

**Comment by Phyks** [comment]
:+1:

**Comment by eliemichel** [comment]
`Plan` sounds like some mistranslation of the French corresponding word, that means more "_projet_" than "_carte_". I would rather use `RoadMap` or something like that.

**Comment by indydedeken** [comment]
@eliemichel i agree
