### ISSUE TITLE
Restore on reload ?

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#3]

**Comment by eliemichel** [comment]
Please be more specific than "_No description provided._"...

**Comment by Phyks** [comment]
I think it was that if one reload the app, she should recover the previously seen app page. Not sure it is a good idea though… and cannot remember adding this issue. 

Le 29 septembre 2015 05:57:32 UTC+02:00, Elie Michel notifications@github.com a écrit :

> Please be more specific than "_No description provided._"...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Phyks/VelibFxos/issues/3#issuecomment-143936901

## 

Phyks

**Comment by eliemichel** [comment]
Isn't that already the case, thanks to the url hash?
This could become a guideline for further development, by the way.

**Comment by Phyks** [comment]
Not sure about it if launched as an app. To be checked. I think this issue was added from an IRC discussion or was split from another one. 

Le 29 septembre 2015 13:58:15 UTC+02:00, Elie Michel notifications@github.com a écrit :

> Isn't that already the case, thanks to the url hash?
> This could become a guideline for further development, by the way.
> 
> Le 29/09/2015 03:14, Lucas Verney a écrit :
> 
> > I think it was that if one reload the app, she should recover the
> > previously seen app page. Not sure it is a good idea though… and
> > cannot
> > remember adding this issue.
> > 
> > Le 29 septembre 2015 05:57:32 UTC+02:00, Elie Michel
> > notifications@github.com a écrit :
> > 
> > > Please be more specific than "_No description provided._"...
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/Phyks/VelibFxos/issues/3#issuecomment-143936901
> > 
> > ## 
> > 
> > Phyks
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Phyks/VelibFxos/issues/3#issuecomment-143969749.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Phyks/VelibFxos/issues/3#issuecomment-144037069

## 

Phyks

**Comment by eliemichel** [comment]
I don't think you can reload it if it is opened as an application.

I mean, you can kill it and restart it, but that should not be part of a 
usual pipeline, and so should not be handled, I think.
