### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#31]
Hi,

Here are some misc issues concerning the actual state of Velib app. These are everything I noticed on the current state of this repo :)

On the home page,
- [x] the black background on hover is useful for debugging, but is not really nice. Tweaking the alpha value should give better results I think.

On the available bikes view,
- [x] the page is higher than the viewport, leading to troubling scroll.
- [x] the map is not always circular. I'd rather make it in a circle border, no ?
- [x] the page is higher than the viewport, leading to troubling scroll.
- [ ] sliding between stations is not super easy, mostly because the part with the map cannot be used for sliding (including the white background around the map)
- [x] as stated in #28, position marker is the same as station marker, which is confusing
- [ ] "+" is not yet implemented
- [ ] "Informations" is in a input, which makes a text cursor appear when clicking on it
- [x] Back image in the header is quite ugly in fact…
- [ ] When switching stations, the map should resize to make both my position and the station position appear (leaflet can handle it easily)
- [x] Looping between stations is no longer possible (on purpose?)
- [ ] Station text could be more stylished and look better :)

On the available stands view,
- [x] some previous comments apply
- [x] it does not show anything

On the favorite view, nothing special

On the search view,
- [x] The position of my search should have its own marker
- [x] Search does not work if geolocation is not available
- [x] Search map is not zoomable

General comments
- [ ] Have you tested it on "poor" hardware such as low tech Android phones or ZTE Open?

**Comment by eliemichel** [comment]
@Phyks Why merging all these issues into a single one? The aim of the issue system is imho to get an advanced TODO-list where we can assign tasks to people, label them, close them, discuss them, etc.

**Comment by eliemichel** [comment]
I added all these issues to single ones, so I close this one.
