### ISSUE TITLE
[Languages] Translation

### ISSUE THREAD

**Issue by indydedeken** [Phyks/VelibFxos#32]
The app will soon contain all text elements, so we could begin to think about the translation implementation.
1. Define a place where the user will be able to change the language?
   - new options page?
   - simplest way...?
2. About implementation, we have different choices:
   - [Mozilla developer - https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization](https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization)
   - [Mozilla contributor - https://github.com/fabi1cazenave/webL10n](https://github.com/fabi1cazenave/webL10n)
   - ...

**Comment by Phyks** [comment]
1. Isn't it possible to get the locale from the system and use it?
2. They use https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization#Add_l10n.js in the WebIDE demo, afaik, and it might be enough and easy to use, no?

**Comment by eliemichel** [comment]
l10n.js seems good. It has been recently presented on Mozilla Hacks and looks like the most confortable solution, although I did not test webL10n.

@Phyks About 1. I think it is almost automatically if the local is correctly declared in manifest.

**Comment by eliemichel** [comment]
Check this out guys:

![CitiBikeFxos on Manhattan](https://raw.githubusercontent.com/eliemichel/CitiBikeFxos/master/doc/screenshot-search.png)

If the CitiBike API was not blocking cross origin requests, it would have taken me litterally 15min to adapt!

We now definitely need i17n!

PS: Available at https://github.com/eliemichel/CitiBikeFxos

**Comment by Phyks** [comment]
\* i18n (or l10n) :p

Concerning i18n, I still think we should implement https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization#Add_l10n.js :)

**Comment by eliemichel** [comment]
Yep, l10n.js is what is proposed in the default app in Firefox WebIDE, and what is used by Gaia.

**Comment by Phyks** [comment]
Will use http://l20n.org/ instead.

**Comment by eliemichel** [comment]
May I ask why?

**Comment by eliemichel** [comment]
It indeed seem nice, but hance I wonder why the official WebIDE does not use it.

**Comment by Phyks** [comment]
https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization#Add_l10n.js

```
For example, at Mozilla we have L20n, a very promising localization project that extends L10n with a variety of compelling new features. Gaia will be moving to L20n fairly soon, but this documentation will still be useful for legacy Firefox OS installs, and other projects.
```

and l10n doc is outdated, l10n is not in its own repo etc etc.

**Comment by eliemichel** [comment]
Ok, it seems pretty reasonable then.

**Comment by Phyks** [comment]
@eliemichel we can use [webl10n](https://github.com/fabi1cazenave/webL10n) or [Jed](https://github.com/SlexAxton/Jed). I am in favor of the first one. Let me know your preference.

**Comment by eliemichel** [comment]
Well, I know l10n and don't know Jed, so let's go for l10n.

**Comment by Phyks** [comment]
@eliemichel HTML content should be localized now. Can you check that I did not forget any string in `index.html`?

Will handle the JavaScript content now.

**Comment by Phyks** [comment]
Known bug: Translation is not done on view change.

**Comment by Phyks** [comment]
JavaScript should be set too. The rule now is to use translated variables for text which is printed to the user, and English for any debugging message.

See the description of https://github.com/hackEns/VelibFxos/commit/c6709cd82dbb88a8d1d616b8f5fbbd0e3f5d27ee for the remaining known bugs. I'm working on it.

**Comment by Phyks** [comment]
- [X] JavaScript translation not working for unknown reason
- [x] Bug with HTML translation (with HTML tags)
- [X] Not retranslating when switching view

@eliemichel I let you check https://github.com/hackEns/VelibFxos/blob/design/js/Views.js, grep `translate` and refactor if you don't like it :)

**Comment by Phyks** [comment]
@eliemichel Updated the JS. Is clean now. Still a small bug with HTML, need update from upstream.

**Comment by eliemichel** [comment]
Quick question: What happens if one change the locale while the application is open?

**Comment by Phyks** [comment]
To be tested, not sure. I think the app will be localized in the new locale upon the next loaded view, which will refresh the screen and then retranslate everything.

**Comment by Phyks** [comment]
@eliemichel This is done and working thanks to https://github.com/hackEns/VelibFxos/commit/062a7cb00e2eba9049cc58c6ecc37ba50d532709 and https://github.com/hackEns/VelibFxos/commit/481b2aec7b38e8e0b217e4a8dee8ca852dd2e7a7!!!
