### ISSUE TITLE
Back image in the header is quite ugly

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#41]
![Ungly back image](https://lut.im/2JzTtuz3/QrQ7I6mM)

**Comment by indydedeken** [comment]
Back image is now [https://github.com/Phyks/VelibFxos/blob/design/css/headers/images/icons/back.svg](https://github.com/Phyks/VelibFxos/blob/design/css/headers/images/icons/back.svg).

Close ?

**Comment by eliemichel** [comment]
Yep, it is checked in @Phyks ' issue so I close it.
