### ISSUE TITLE
Homogenize margins

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#46]
On that example, right margin and top margin should be the same:
![bad margin](https://lut.im/ffIMTUZB/6WNFLfvb)

**Comment by indydedeken** [comment]
@eliemichel How did you get this that ?

**Comment by eliemichel** [comment]
Openning the app in Firefox (desktop) or on my Flame, whichever the width is.

**Comment by indydedeken** [comment]
Never seen this problem, @eliemichel maybe you correct it with a css commit ?

**Comment by Phyks** [comment]
Yep, @eliemichel closed it :)
