### ISSUE TITLE
Precise parseInt radix

### ISSUE THREAD

**Issue by indydedeken** [Phyks/VelibFxos#6]
A radix must be precised for parseInt method in <code>app.js</code>. 

Actually <code>app.js</code> : 

<pre>// Returns `limit` closest stations with up to date infos and a matching criterion
[...]
limit = parseInt(limit);
</pre>

Replace with : 

<pre>// Returns `limit` closest stations with up to date infos and a matching criterion
[...]
limit = parseInt(limit, 10);
</pre>

Mozilla doc says :

> If the input string begins with "0", radix is eight (octal) or 10 (decimal).  Exactly which radix is chosen is implementation-dependent.  ECMAScript 5 specifies that 10 (decimal) is used, but not all browsers support this yet.  **For this reason always specify a radix when using parseInt.**

See : [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)

**Comment by eliemichel** [comment]
Thanks for this precision, I did not know about it!

**Comment by Phyks** [comment]
Same here, thanks! :)

**Comment by Phyks** [comment]
My bad, I closed thinking you had included it in the PR, but not.
