### ISSUE TITLE
Add a link from station detail to its position in the search view

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#77]
We could use the top right-hand corner icon of the station's detail view as a link to the search view, centered on the current station.

**Comment by Phyks** [comment]
:+1:

Le 29 septembre 2015 06:01:25 UTC+02:00, Elie Michel notifications@github.com a écrit :

> We could use the top right-hand corner icon of the station's detail
> view as a link to the search view, centered on the current station.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Phyks/VelibFxos/issues/77

## 

Phyks
