### ISSUE TITLE
Avoid displaying too many markers at the same time

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#81]
I don't know exactly how to handle it, but when people zoom out too much, basically all the markers are displayed, and so it is very slow.

Maybe disabling all the markers when zoom is too out, to mean people not to do so?

**Comment by indydedeken** [comment]
Maybe we can use a marker clustering plugin for Leaflet ?

For example : https://github.com/Leaflet/Leaflet.markercluster
It seems fast and customizable on the demo.

**Comment by eliemichel** [comment]
Looks great!

**Comment by eliemichel** [comment]
Done in f02346c
It would be nice to customize it eventually, but it works very well out of the box!
