### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#83]
There seem that there is no licence for this project!
I will add a `LICENCES` file with at least licence and acknowledgements to external libraries we use.

I suggest something like MIT or BSD.

PS: I am very surprised, I though we already had this discussion…

**Comment by eliemichel** [comment]
Is `Control.OSMGeocoder` an external dependency?

**Comment by Phyks** [comment]
I think so. I'm in favor of MIT. We had this discussion on other codes, not this one :)

\* LICENSES in english :p

**Comment by Phyks** [comment]
@eliemichel yw https://github.com/k4r573n/leaflet-control-osm-geocoder

**Comment by eliemichel** [comment]
@Phyks Yep, but it has been hacked:

https://github.com/Phyks/VelibFxos/blame/design/js/Control.OSMGeocoder.js

TODO: Clean that up!
