### ISSUE TITLE
Distance in bikes / stands view

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#95]
Shouldn't they be in meters rather than kilometers? At least for the first ones. "200m" is better than "0.2km" I think.

**Comment by eliemichel** [comment]
I agree.

From an architecture point of view, we should have something like a `distancePrettyPrinter`, as well as a `timePrettyPrinter` and so on. We already have something like `formatStation`.

**Comment by Phyks** [comment]
Closed by https://github.com/Phyks/VelibFxos/commit/fcc75efc63aca143ec91138870a64416d792f352.
