### ISSUE TITLE
Search map without current position marker

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#97]
When going back from station details to search map, the current position marker is not there anymore.

**Comment by Phyks** [comment]
Actually it is because we are in a "search station" view, see issue #90.

**Comment by eliemichel** [comment]
For me the icon of the position marker is always broken.
But the fact that it completely disappear is another issue, indeed.

**Comment by Phyks** [comment]
Broken position marker was fixed today, see another issue :)

**Comment by eliemichel** [comment]
Ah ok =)

**Comment by Phyks** [comment]
@eliemichel should be fixed. We should check there is no memory leak.

**Comment by eliemichel** [comment]
@Phyks please try to always link the issue to the commit solving it.
I you forgot to include "Fix #97" in the body of the commit, which would also automatically close the issue, just give the small hash of the commit in the closing comment.
