### ISSUE TITLE
Center on me

### ISSUE THREAD

**Issue by Phyks** [Phyks/VelibFxos#99]
I think we should have a "center on me" button in the map view, to be able to quickly find back our position.

**Comment by eliemichel** [comment]
Yep, and on the other hand I noticed that the view is regularely recenterd on the current position. Really anoying, we should disable that.

**Comment by Phyks** [comment]
True, everytime the position is updated (every second or so), the callback function pans the map to the current position. We should disable it.

**Comment by Phyks** [comment]
@eliemichel the `panTo` was left few lines below. This is now fixed.
